/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as HorasRouteImport } from './routes/horas'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const HorasRoute = HorasRouteImport.update({
  id: '/horas',
  path: '/horas',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/financeiro': typeof FinanceiroRoute
  '/historico': typeof HistoricoRoute
  '/horas': typeof HorasRoute
  '/importar': typeof ImportarRoute
  '/lancamentos': typeof LancamentosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/financeiro': typeof FinanceiroRoute
  '/historico': typeof HistoricoRoute
  '/horas': typeof HorasRoute
  '/importar': typeof ImportarRoute
  '/lancamentos': typeof LancamentosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/financeiro': typeof FinanceiroRoute
  '/historico': typeof HistoricoRoute
  '/horas': typeof HorasRoute
  '/importar': typeof ImportarRoute
  '/lancamentos': typeof LancamentosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/financeiro'
    | '/historico'
    | '/horas'
    | '/importar'
    | '/lancamentos'
    | '/reset-password'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/financeiro'
    | '/historico'
    | '/horas'
    | '/importar'
    | '/lancamentos'
    | '/reset-password'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/financeiro'
    | '/historico'
    | '/horas'
    | '/importar'
    | '/lancamentos'
    | '/reset-password'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FinanceiroRoute: typeof FinanceiroRoute
  HistoricoRoute: typeof HistoricoRoute
  HorasRoute: typeof HorasRoute
  ImportarRoute: typeof ImportarRoute
  LancamentosRoute: typeof LancamentosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horas': {
      id: '/horas'
      path: '/horas'
      fullPath: '/horas'
      preLoaderRoute: typeof HorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FinanceiroRoute: FinanceiroRoute,
  HistoricoRoute: HistoricoRoute,
  HorasRoute: HorasRoute,
  ImportarRoute: ImportarRoute,
  LancamentosRoute: LancamentosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
